token = "your token here"
outgoing_channel = "#some-event-channel"
removal_timeout_secs = 1900
forced_timeout_secs = 86400
notify_on_start = false
reaction_on_start = true
reaction_trigger = "robot_face"
